<?php
$title = 'Add new chat';
$this->headTitle($title);

$this->form->setAttribute('action', $this->url('chat', array('action' => 'add')));
$this->form->prepare();
?>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">Chat details</div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <?php 
                echo $this->form()->openTag($this->form);
                $chat = $this->form->get('chat');
                ?>
                <div class="form-group">
                    <?php echo $this->formLabel($chat->get('title')); ?>
                    <?php echo $this->formElement($chat->get('title')); ?>
                </div>
                <?php
                echo $this->formHidden($this->form->get('csrf'));
                echo $this->formElement($this->form->get('submit'));
                
                echo $this->form()->closeTag();
                ?>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
