<?php
$title = 'Edit user';
$this->headTitle($title);

/** @var \Chatter\Entity\User $user */
$this->user = $user;

$this->form->setAttribute('action', $this->url('user', array('action' => 'edit', 'id' => $this->user->getId())));
$this->form->prepare();
?>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">User details</div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <?php
                echo $this->form()->openTag($this->form);
                $user = $this->form->get('user');
                echo $this->formHidden($user->get('id'));
                ?>
                <div class="form-group">
                    <?php echo $this->formLabel($user->get('name')); ?>
                    <?php echo $this->formElement($user->get('name')); ?>
                </div>
                <?php
                echo $this->formHidden($this->form->get('csrf'));
                echo $this->formElement($this->form->get('submit'));
                
                echo $this->form()->closeTag();
                ?>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">Friends</div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="list-group">
                    <?php foreach($this->user->getMyFriends() as $friend): ?>
                        <a href="#" class="list-group-item">
                            <i class="fa fa-user"></i> <?php echo $friend->getName(); ?>
                        </a>
                    <?php endforeach; ?>
                    <?php foreach($this->user->getFriendsWithMe() as $friend): ?>
                        <a href="#" class="list-group-item">
                            <i class="fa fa-user"></i> <?php echo $friend->getName(); ?>
                        </a>
                    <?php endforeach; ?>
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
