<?php

$title = 'Users';
$this->headTitle($title);
?>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">All the users</div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->users as $user) : ?>
                                <tr>
                                    <td><?php echo $user->getId(); ?></td>
                                    <td><?php echo $this->escapeHtml($user->getName()); ?></td>
                                    <td><a href="<?php echo $this->url('user', array('action'=>'edit', 'id' => $user->getId())); ?>">Edit</a></td>
                                    <td><a href="<?php echo $this->url('user', array('action'=>'delete', 'id' => $user->getId())); ?>">Delete</a></td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <a class="btn btn-primary" href="<?php echo $this->url('user', array('action'=>'add'));?>">Add new user</a>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->






