<?php
$title = 'Edit message';
$this->headTitle($title);

$this->form->setAttribute('action', $this->url('message', array('action' => 'edit', 'id' => $this->message->getId())));
$this->form->prepare();
?>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading"> details</div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <?php
                echo $this->form()->openTag($this->form);
                $message = $this->form->get('message');
                echo $this->formHidden($message->get('id'));
                ?>
                <div class="form-group">
                    <?php echo $this->formLabel($message->get('text')); ?>
                    <?php echo $this->formElement($message->get('text')); ?>
                </div>
                <?php
                echo $this->formHidden($this->form->get('csrf'));
                echo $this->formElement($this->form->get('submit'));
                
                echo $this->form()->closeTag();
                ?>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
