<?php

$title = 'Messages';
$this->headTitle($title);
?>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">All the messages</div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Date created</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->messages as $message) : ?>
                                <tr>
                                    <td><?php echo $message->getId(); ?></td>
                                    <td><?php echo $this->escapeHtml($message->getText()); ?></td>
                                    <td><?php echo $message->getDateCreated()->format('Y-m-d H:i:s'); ?></td>
                                    <td><a href="<?php echo $this->url('message', array('action'=>'edit', 'id' => $message->getId())); ?>">Edit</a></td>
                                    <td><a href="<?php echo $this->url('message', array('action'=>'delete', 'id' => $message->getId())); ?>">Delete</a></td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <a class="btn btn-primary" href="<?php echo $this->url('message', array('action'=>'add'));?>">Add new message</a>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->






